### ISSUE TITLE
CIを追加

### ISSUE THREAD

**Issue by yassi-github** [higuruchi/injesh#11]
push,pullreq

- test
- build
- clippy
- doc

とりあえずこれぐらい？

rustdocをgithub.ioに公開も必要ならやるが，
現状ドキュメント書いてないからな～

どうすべ？

**Comment by higuruchi** [comment]
`rustdoc `は今は必要ないんじゃないかな。ver 1.0.0が見えてきたらくらいで
testとbuildは欲しいね

**Comment by yassi-github** [comment]
ではrustdocは今んとこなしで．

clippyはどうしよか．エラー吐く設定だと現状ほとんどのactionsの結果に ❌ マークがつく．
errorでなくwarningを出すようにして，buildやtestに失敗した時だけ ❌ にしたほうがダレなくていいかもと思ったがいかがか？

**Comment by higuruchi** [comment]
そんな感じでよろしく

**Comment by yassi-github** [comment]
check #13
