### ISSUE TITLE
injesh homedirを表す変数の共有化

### ISSUE THREAD

**Issue by yassi-github** [higuruchi/injesh#14]
各サブコマンドで環境変数homeから`~/.injesh/*`を生成して使うのは，処理が重複してるので共通化したい

案

1. command.rsかどこか に `const INJESH_HOME = ~/.injesh`, `const INJESH_HOME_IMAGE = INJESH_HOME/images` などを設定する
  - HomePath みたいな structかenumか 作ってそれにまとめるのでもいいかも
2. 環境変数からPathを生成する関数を定義し，各サブコマンドの実行時にそれを呼び出す

実行ごとに変数が初期化されるなら1.でよさそう．
struct等にまとめるか否か．まとめて使うのがめんどくさくなるなら，変数だけでいいと思うがどう？

**Comment by higuruchi** [comment]
そんなに数は多くないしcomment.rs内にconstで定義してあげるのが良さげ

**Comment by higuruchi** [comment]
initの方mergeしちゃって、別のプルリクで対応する？

**Comment by higuruchi** [comment]
やっぱり、別のパッケージ用意してそこに構造体なりを定義してあげた方がいいかな

command.rsとuser.rsみたいに

そもそも、commandパッケージとホームディレクトリとかを管理する機能では管理する範囲が異なるので

**Comment by higuruchi** [comment]
それらをcommand.rsのExec構造体みたいに書くコマンドの引数に渡してあげるのがいいと思う

**Comment by yassi-github** [comment]
ならば，`utils.rs`をつくってそこにhomedirの構造体を放り込んでおく？
`utils.rs`にはコンテナidからpid求める関数やらを定義する予定．

**Comment by higuruchi** [comment]
users.rsはcommand.rsと同じようにドメイン(最重要データ構造)を想定しているので雑に放り込むと色々と不都合が起こる

**Comment by higuruchi** [comment]
command.rsと同じ階層にuser.rs的なのを生やして、initやlaunchのインタフェースにuser構造体を引数に追加すれば良いのでは？

**Comment by yassi-github** [comment]
users.rs ? utils.rs ？
まあつまり，utils.rsはインタフェースやハンドラのモジュールのように変更しまくったらヤバいタイプのモジュールになる…ってこと？

そしてutils.rsとは別のモジュールを作ってそこでhomedirの構造体を定義すべき…ってこと？

**Comment by yassi-github** [comment]
引数にわたすと変更がしんどそう．
utils::HomePath::new();みたいにすると構造体を生成できるようにできればよさそうだがいかがか

**Comment by higuruchi** [comment]
users.rs : ユーザの情報などを管理するパッケージ
utils.rs : 便利関数を色々集めたパッケージ

> そしてutils.rsとは別のモジュールを作ってそこでhomedirの構造体を定義すべき…ってこと？

そう

そもそもパッケージを分ける理由について、任意のパッケージやクラスを変更する理由は１つでないといけないから

**Comment by higuruchi** [comment]
user構造体をutilsに入れたとして、.injeshディレクトリの場所などを変更する際、utilなどを変更することとなる。

だけど、utilはcontainer nameからPIDを取ってくる関数などが入ってる

別の理由での変更が入ってコンフリクトが発生するかもしれない

**Comment by higuruchi** [comment]
> 引数にわたすと変更がしんどそう．

まあ、そこはしょうがない。
まだ初期段階だから救われたと思おう

**Comment by yassi-github** [comment]
役割の範囲が微妙に違うのに同じモジュールにまとめてしまうと，
他のなんらかが引き起こしたutilsモジュールへの変更が，同じモジュールに定義していたばかりに変更を強いられるかもしれず，それによるコンフリクトが考えられる…ということか．
役割毎に分けたほうがわかりやすいし，utilsでないusersに定義するのでよさそう．

**Comment by higuruchi** [comment]
頼んじゃってもいい？

**Comment by yassi-github** [comment]
引数に渡すのに関して疑問が残るんだが，
今後，オリジナルの環境変数を用意することもありえなくはないと思う．
そこで，各コマンドでオリジナルの環境変数を使うってなったときも，このように引数を増やしていくの？となると変更量やばいことになりそう．

**Comment by higuruchi** [comment]
users.rsにして、command.rsの中のそれぞれの構造体に環境変数とかを突っ込んでいけば引数は変更せずに使えそう

**Comment by higuruchi** [comment]
```rust
pub struct Exec {
    name: String,
    cmd: Option<String>
    home: String
    user: String
}

```
みたいな感じに

**Comment by higuruchi** [comment]
これをやろうとするとparser.rsをいじらないといけないの

**Comment by yassi-github** [comment]
となると，変更を加える必要があるのは command.rs の構造体定義のみになるというわけか．
ん，parser.rs もいじるのか…？それは…しんどいぞ

**Comment by higuruchi** [comment]
そうやね〜
これは僕が実装した方がいいか？

**Comment by yassi-github** [comment]
ではよろしく頼みます
