### ISSUE TITLE
user.rsあたりで，ユーザーのCPUアーキテクチャを取得する

### ISSUE THREAD

**Issue by yassi-github** [higuruchi/injesh#32]
現在はハードコードしている．

---

おそらくの対応表

|uname|architecture|
|---------|-------------|
|x86_64|amd64|
|aarch64|arm64|
|armv7l|armhf|
|armv6l|armhf|
...

RPI 4は`aarch64`で，`arm64`に対応しているっぽい(aptのパッケージソースがarm64だった)ことが確認できた．

他のarmアーキテクチャは`armv7l`など`arm*`のバリエーションがあるっぽい．
さらにそれらは`armhf`にあたりそう．RPI 3あたりで試してみたい．

---

unameシステムコールを使えばCPUアーキテクチャの種類がとれた

```c
#include <stdio.h>
#include <sys/utsname.h>

int main() {
        struct utsname buf[32];
        uname(buf);
        printf("%s\n", buf -> machine);
        return 0;
}
```

**Comment by higuruchi** [comment]
アーキテクチャとってくるのはどちらかというとuser.rsの方が良いのでは？

**Comment by higuruchi** [comment]
アーキテクチャもユーザ依存の情報な訳だし

**Comment by yassi-github** [comment]
せやな

**Comment by yassi-github** [comment]
モジュール分けなくても、各処理で
```rust
println!("machine: {}", nix::sys::utsname::uname().machine());
// Output:
//  machine: x86_64
```
のように呼び出せば済む。

よって、わざわざ関数を作ってやらなくていいかなと思う

**Comment by yassi-github** [comment]
もしくは、`User`構造体に`architecture`メンバでも追加してやって、そこに`String`を入れる？
何回もシステムコールしなくて済むメリットはある。

**Comment by yassi-github** [comment]
対応表に合わせて出力変えなあかんからUser構造体にメンバ追加する方式でいきます
