### ISSUE TITLE
container.rsにreloadモジュールを追加

### ISSUE THREAD

**Issue by higuruchi** [higuruchi/injesh#42]
# 内容

デバック対象コンテナをreloadするためのモジュールをcontainer.rsを追加

**Comment by yassi-github** [comment]
単にメソッドを実装する https://github.com/higuruchi/injesh/pull/38/commits/076d010609c2940721860439d3ee8999e0f9c350 のはだめなの？

**Comment by higuruchi** [comment]
気づかんかった。ごめそ
